name: Backend PR Pipeline

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-pr.yml'

jobs:
  backend-pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with StyleCop
        run: dotnet build /p:TreatWarningsAsErrors=true

      - name: Security scan
        run: dotnet list package --vulnerable

      - name: Run unit tests with coverage
        run: |
          dotnet test TaskManagement.Tests/TaskManagement.Tests.csproj --collect:"XPlat Code Coverage" --filter "Category=Unit"
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi

      - name: Run integration tests with coverage
        run: |
          dotnet test TaskManagement.Tests/TaskManagement.Tests.csproj --collect:"XPlat Code Coverage" --filter "Category=Integration"
          if [ $? -ne 0 ]; then
            echo "Integration tests failed"
            exit 1
          fi

      - name: Check coverage thresholds
        run: |
          # ユニットテストのカバレッジチェック
          if [ $(grep -o '"lineRate": [0-9]*\.[0-9]*' coverage/unit/coverage.cobertura.xml | grep -o '[0-9]*\.[0-9]*' | awk '{print int($1 * 100)}') -lt 85 ]; then
            echo "Unit test line coverage is below 85%"
            exit 1
          fi
          if [ $(grep -o '"branchRate": [0-9]*\.[0-9]*' coverage/unit/coverage.cobertura.xml | grep -o '[0-9]*\.[0-9]*' | awk '{print int($1 * 100)}') -lt 75 ]; then
            echo "Unit test branch coverage is below 75%"
            exit 1
          fi

          # インテグレーションテストのカバレッジチェック
          if [ $(grep -o '"lineRate": [0-9]*\.[0-9]*' coverage/integration/coverage.cobertura.xml | grep -o '[0-9]*\.[0-9]*' | awk '{print int($1 * 100)}') -lt 60 ]; then
            echo "Integration test line coverage is below 60%"
            exit 1
          fi
          if [ $(grep -o '"branchRate": [0-9]*\.[0-9]*' coverage/integration/coverage.cobertura.xml | grep -o '[0-9]*\.[0-9]*' | awk '{print int($1 * 100)}') -lt 50 ]; then
            echo "Integration test branch coverage is below 50%"
            exit 1
          fi

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-reports
          path: |
            backend/coverage/unit
            backend/coverage/integration
          retention-days: 7
