name: Frontend PR Pipeline

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pr.yml'

jobs:
  frontend-pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run type-check

      - name: ESLint check
        run: npm run lint

      - name: Prettier check
        run: npm run format

      - name: Security scan
        run: npm run security-scan

      - name: Run unit tests with coverage
        run: |
          npm run test:coverage
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi

      - name: Run integration tests with coverage
        run: |
          npm run test:integration:coverage
          if [ $? -ne 0 ]; then
            echo "Integration tests failed"
            exit 1
          fi

      - name: Check coverage thresholds
        run: |
          # ユニットテストのカバレッジチェック
          if [ $(grep -o '"lines": [0-9]*' coverage/unit/coverage-summary.json | grep -o '[0-9]*') -lt 60 ]; then
            echo "Unit test line coverage is below 60%"
            exit 1
          fi
          if [ $(grep -o '"branches": [0-9]*' coverage/unit/coverage-summary.json | grep -o '[0-9]*') -lt 50 ]; then
            echo "Unit test branch coverage is below 50%"
            exit 1
          fi

          # インテグレーションテストのカバレッジチェック
          if [ $(grep -o '"lines": [0-9]*' coverage/integration/coverage-summary.json | grep -o '[0-9]*') -lt 80 ]; then
            echo "Integration test line coverage is below 80%"
            exit 1
          fi
          if [ $(grep -o '"branches": [0-9]*' coverage/integration/coverage-summary.json | grep -o '[0-9]*') -lt 70 ]; then
            echo "Integration test branch coverage is below 70%"
            exit 1
          fi

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-reports
          path: |
            frontend/coverage/unit
            frontend/coverage/integration
          retention-days: 7 